### ISSUE TITLE
compilation error messages are truncated

### ISSUE THREAD

**Issue by tbrown122387** [maverickg/cxxfunplus#1]
Is there a way I can view compilations errors in an untruncated form? I'm trying to compile some heavily-templated code, and I can't see what's going wrong.

Can we remove the `tail()` part somehow below?

```
Error in compileCode(f, code, language = language, verbose = verbose) :
/home/trb5me_admin/R/x86_64-pc-linux-gnu-library/4.2/RcppEigen/include/Eigen/src/Core/Redux.h:453:73: required from ‘typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::sum() const [with Derived = Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs2_op<double>, const Eigen::Solve<Eigen::LLT<Eigen::Matrix<double, 3, 3>, 1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 3, 1>, const Eigen::Matrix<double, 3, 1> > > >; typename Eigen::internal::traits<T>::Scalar = double]’/home/trb5me_admin/R/x86_64-pc-linux-gnu-library/4.2/RcppEigen/include/Eigen/src/Core/Dot.h:98:22: required from ‘typename Eigen::NumTraits<typename Eigen::internal::traits<T>::Scalar>::Real Eigen::MatrixBase<Derived>::squaredNorm() const [with Derived = Eigen::Solve<Eigen::LLT<Eigen::Matrix<double, 3, 3>, 1>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::Matrix<double, 3, 1>, const Eigen:

5.
stop(tail(errmsg))
4.
compileCode(f, code, language = language, verbose = verbose)
3.
cxxfunction(sig = sig, body = body, plugin = plugin, includes = includes,
settings = settings, ..., verbose = verbose)
2.
cxxfunplus::cxxfunctionplus(methods::signature(), plugin = "pfr",
includes = inc, save.dso = save, verbose = TRUE) at compile.R#53
1.
buildModelFuncs(".", "mean_factor_msvol")
```

**Comment by maverickg** [comment]
Change the source code and install it from source?
  
  
  
  
  
  
  

  
  
>

**Comment by tbrown122387** [comment]
Change the source code of what?  `cxxfunctionplus()` or `cxxfunction()`? Everything north of that is from source.

**Comment by maverickg** [comment]
I was referring to the code in this package. But I am sorry in that it’s not an option in this package. (This code has not been looked for over 10 years. I thought no one is using this package. It was more of playing around getting a package to CRAN at the time.)
  

 You might need to dig deeper into package inline and see if you can do something. For example, trying to use option warning.length as it’s used in function compileCode in package inline.
  
  
  
  
  
  

  
  
>

**Comment by tbrown122387** [comment]
ten years! wow, didn't notice that. I saw [this](https://github.com/stan-dev/rstan/blob/71ab1409531c2c5e412635482fee545c77e2a070/rstan/rstan/R/cxxfunplus.R#L138) in stan, and I thought it would be more appropriate to reference a package rather than copy/paste that
